### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bioce** [bioce/bioce.github.io#1]
### todo list

- [x] `HashMap` 和 `Hashtable` 的区别
- [ ] `AbstractQueuedSynchronizer` 即 `AQS`
- [x] 缓存穿透和缓存雪崩
- [x] CAP原则
- [x] 数据库事务，事务级别
- [x] mysql默认事务级别，原因
- [ ] 数据库的锁，乐观锁、悲观锁
- [ ] mysql分库分表相关
- [ ] MVCC
- [ ] 分布式事务、两阶段提交、三阶段提交
- [ ] 负载均衡策略
- [ ]

**Comment by bioce** [comment]
### `HashMap` 和 `Hashtable` 的区别

- HashMap 线程不安全，Hashtable 线程安全（使用synchronized同步）
- 在单线程条件下，Hashtable由于同步，速度较慢
- HashMap支持 `Key = null`，放在第0个桶里，Hashtable不支持 `Key = null`

使用建议：
- 单线程情况下用 `HashMap`
- 多线程情况下用 `ConcurrentHashMap`

**Comment by bioce** [comment]
### 缓存穿透

大量访问不存在的数据时，会将请求全部打到DB上，导致缓存穿透

- 使用BloomFilter
一定不存在的数据会被BloomFilter拦截掉；但是这种方式需要将所有数据放到BloomFilter中，有一定局限性
- 数据不存在时，将不存在的结果也缓存起来

### 缓存雪崩

大量缓存同时失效时，瞬间大量的请求落到底层系统中，对系统造成大的冲击

- 单线程去更新缓存失效的数据
- 缓存时间分散开，可以在缓存时间+随机时间，避免集体失效

### 缓存击穿

缓存击穿和雪崩类似，不过击穿是单个热key缓存失效，冲击DB

### 听说过的其他问题

1. 未了避免缓存失效，有个服务定时刷缓存数据，结果提供数据的服务有问题，更新了空数据进去，导致全部无数据

**Comment by bioce** [comment]
### CAP原则

- Consistency: 一致性
- Availability: 可用性
- Partition tolerance: 分区容错

一般人们解释为：在分布式系统中，C、A、P三者最多同时满足两个；
1. AP，网络分区的情况下，分隔的节点不能相互通信，但同时对外服务，将导致状态不一致，即不能满足C
2. CP，网络分区的情况下，分隔的节点不能相互通信，为达成C，请求只能一直等待，不提供服务，即不满足A。
3. CA，在一定时间内要达到节点状态一致，要求不能出现网络分区，则不能满足P。

还有理解为：当网络发生分区的情况下，C和A不能完全满足；如果对一致性要求高，可以提供部分数据查询功能，保证系统的部分可用；如果对系统可用性要求高，可以牺牲部分一致性，做到最终一致性；

- 不同的业务系统的选择不同
- 一般意义上，银行系统为了一致性会放弃部分可用性；只提供查询服务
- 为了保证分布式中间件的可用性，大部分中间件会支持最终一致性

**Comment by bioce** [comment]
### mysql事务级别

- [互联网项目中mysql应该选什么事务隔离级别](https://zhuanlan.zhihu.com/p/59061106)

**Comment by bioce** [comment]
### 数据库事务

#### 事务

多个操作要么全部执行成功，要么都不执行

#### 数据库事务的四个特征：ACID

- Atomic（原子性）：指事务是一个不可分割的工作单位，事务中的操作要么全部成功，要么全部失败
- Consistency（一致性）：事务必须使数据库从一个一致性状态变换到另外一个一致性状态
- Isolation（隔离性）：多个用户并发访问数据库时，数据库为每一个用户开启的事务，不能被其他事务的操作数据所干扰，多个并发事务之间要相互隔离
- Durability（持久性）：指一个事务一旦被提交，它对数据库中数据的改变就是永久性的

#### 事务的隔离级别

- 串行化：最严格的级别，事务串行执行，资源消耗最大，一般不会采用
- 可重复读：保证了一个事务不会修改已经由另一个事务读取但未提交（回滚）的数据。避免了“脏读取”和“不可重复读取”的情况，但不能避免“幻读”，但是带来了更多的性能损失
- 读已提交：大多数主流数据库的默认事务等级，保证了一个事务不会读到另一个并行事务已修改但未提交的数据，避免了“脏读取”，但不能避免“幻读”和“不可重复读取”。该级别适用于大多数系统
- 读未提交：事务中的修改，即使没有提交，其他事务也可以看得到，会导致“脏读”、“幻读”和“不可重复读取”，一般不会采用

#### 脏读、不可重复读、幻读

- 脏读：所谓的脏读，其实就是读到了别的事务回滚前的脏数据。比如事务B执行过程中修改了数据X，在未提交前，事务A读取了X，而事务B却回滚了，这样事务A就形成了脏读。也就是说，当前事务读到的数据是别的事务想要修改成为的但是没有修改成功的数据。
- 不可重复读：事务A首先读取了一条数据，然后执行逻辑的时候，事务B将这条数据改变了，然后事务A再次读取的时候，发现数据不匹配了，就是所谓的不可重复读了。也就是说，当前事务先进行了一次数据读取，然后再次读取到的数据是别的事务修改成功的数据，导致两次读取到的数据不匹配，也就照应了不可重复读的语义。
- 幻读：事务A首先根据条件索引得到N条数据，然后事务B改变了这N条数据之外的M条或者增添了M条符合事务A搜索条件的数据，导致事务A再次搜索发现有N+M条数据了，就产生了幻读。也就是说，当前事务读第一次取到的数据比后来读取到数据条目少。

#### 不可重复读和幻读比较：

脏读是指一个事务读取到了其他事务没有提交的数据，不可重复读是指一个事务内多次根据同一个查询条件查询出来的同一行记录的值不一样，幻读是指一个事务内多次根据同个条件查出来的记录行数不一样
